apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
spec:
  replicas: 4
  serviceName: sts-svc-domain #statefulset need it
  selector:
    matchLabels:
      app: sts
  template:
    metadata:
      labels:
        app: sts
    spec:
      containers:
      - name: nginx 
        image: nginx 
