apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secretkeyref
  name: secretkeyref
spec:
  containers:
  - image: sysnet4admin/mysql-auth 
    name: mysql-auth 
    env:
    - name: MYSQL_USER_ID
      valueFrom:
         secretKeyRef:
           name: mysql-cred 
           key: username 
    - name: MYSQL_USER_PASSWORD
      valueFrom:
         secretKeyRef:
           name: mysql-cred 
           key: password 
#    - name: MYSQL_ROOT_PASSWORD 
#      valueFrom:
#         secretKeyRef:
#           name: mysql-cred 
#           key: root_password  
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-pvc
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-pvc
    persistentVolumeClaim:
      claimName: mysql-pvc
