apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-nginx 
  template:
    metadata:
      labels:
        app: rollout-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.1
