apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nslookup
  name: nslookup
spec:
  containers:
  - image: sysnet4admin/net-tools
    name: net-tools
    command: ["/bin/sh", "-c"]
    args:
    - sleep 3600

