apiVersion: batch/v1
kind: Job
metadata:
  name: job-completions 
spec:
  completions: 3
  template:
    spec:
      containers:
      - name: job-completions
        image: sysnet4admin/net-tools
        command: ["curlchk",  "nginx"]
      restartPolicy: Never
