apiVersion: v1
kind: Pod
metadata:
  labels:
    run: po-chk-hn
  name: po-chk-hn
spec:
  containers:
  - image: sysnet4admin/chk-hn 
    name: chk-hn
---
apiVersion: v1
kind: Service
metadata:
  name: cl-chk-hn 
spec:
  selector:
    run: po-chk-hn  
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

