apiVersion: v1
kind: Pod
metadata:
  labels:
    run: readinessprobe-exec
  name: readinessprobe-exec
spec:
  containers:
  - name: tardy-nginx 
    image: sysnet4admin/tardy-nginx 
    readinessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy-on
      initialDelaySeconds: 10
      periodSeconds: 5
