apiVersion: v1
kind: Pod
metadata:
  name: nodeAffinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: inmemory
            operator: In
            values:
            - redis
  containers:
  - name: nginx
    image: nginx

