apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configmapkeyref
  name: configmapkeyref
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmapkeyref
  template:
    metadata:
      labels:
        app: configmapkeyref
    spec:
      containers:
      - image: sysnet4admin/sleepy 
        name: sleepy 
        command: ["/bin/sh","-c"]
        args:
        - |
          echo "sleepy is $APP_STATUS"
          sleep 3600
        env:
        - name: APP_STATUS # mandantory field
          valueFrom:
            configMapKeyRef:
              name: sleepy-config
              key: STATUS
