apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aks-topologyspreadconstraints
  name: aks-topologyspreadconstraints
spec:
  replicas: 9
  selector:
    matchLabels:
      app: aks-topologyspreadconstraints
  template:
    metadata:
      labels:
        app: aks-topologyspreadconstraints
    spec:
      containers:
      - image: nginx
        name: nginx
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/region
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: aks-topologyspreadconstraints
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: aks-topologyspreadconstraints
